package com.pypypraful.einvoicing.persistence.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.Date;

import static com.pypypraful.einvoicing.persistence.dynamodb.InventoryTableConstants.CUSTOMER_ID;
import static com.pypypraful.einvoicing.persistence.dynamodb.InventoryTableConstants.EXECUTION_NAME;
import static com.pypypraful.einvoicing.persistence.dynamodb.InventoryTableConstants.WORKFLOW_METADATA_TABLE_NAME;

@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@DynamoDBTable(tableName = WORKFLOW_METADATA_TABLE_NAME)
public class DBWorkflowMetadata {

    @DynamoDBHashKey(attributeName = CUSTOMER_ID)
    private String customerId;

    @DynamoDBRangeKey(attributeName = EXECUTION_NAME)
    private String executionName;

    @DynamoDBAttribute(attributeName = "stepTaskToken")
    private String stepTaskToken;

    @DynamoDBAttribute(attributeName = "workflowType")
    private String workflowType;

    @DynamoDBAttribute(attributeName = "status")
    private String status;

    @DynamoDBAttribute(attributeName = "execution_arn")
    private String executionArn;

    @DynamoDBAttribute(attributeName = "lastUpdationDateInMillis")
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date lastUpdationDateInMillis;

    @DynamoDBAttribute(attributeName = "creationDateInMillis")
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date creationDateInMillis;
}
